# Generated by Django 4.0.5 on 2022-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTestJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('test_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestInformation',
            fields=[
                ('test_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(default=30)),
                ('neg_mark', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
                ('proctor_type', models.CharField(choices=[('0', 'Automatic Monitoring'), ('1', 'Live Monitoring')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('ans', models.CharField(max_length=1)),
                ('marks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestSubjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('question_id', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('marks', models.CharField(max_length=500)),
            ],
        ),
    ]
